### ISSUE TITLE
Create a dedicated profile settings page

### ISSUE THREAD

**Issue by ByteOtter** [ByteOtter/OtterDen#52]
Maybe there should he a dedicated settings page where users can choose several settings to cistomize their experience.

- [x] Hide their mail address (default: yes)
- [x] Hide their posts (default: no)
More to come ...

TODO:

- [x] Add two booleans to the `user` model: `hide_email : default = True` and `hide_posts : default = False`
- [x] Migrate the database to these new models
- [x] Add the two booleans to the `account` route
  - [x] Pre populate the `account` form with the current values for `hide_email` and `hide_posts`
  - [x] Accept the changed values from the switches on the form and set them in the database
- [x] Change all necessary templates to hide this information where necessary:
  - [x] `post.html` should hide/unhide mail adress
  - [x] `user_profile.html` should hide/unhide mail adress
  - [x] `home.html` should not show posts from users who set their posts to private
  - [x] `user/history/<username>` route should **not** be accessible to unauthorized users when posts are set to private (throw `403 forbidden`

**Comment by ByteOtter** [comment]
Added navigational dropdown and dummy settings to the settings page

![Screenshot](https://user-images.githubusercontent.com/90576030/217241357-41a011f9-b1be-4caf-ad31-dab2210bcfff.png)
