### ISSUE TITLE
[FR:] Allow users to tag their posts aswell as find them by these tags

### ISSUE THREAD

**Issue by ByteOtter** [ByteOtter/OtterDen#92]
# You would like to suggest a new feature?

Right now Posts can only be found either all at once on the home page or by directly typing in a username.
To change this users should be allowed to tag their posts so other users can find them either by search for them manually in statically themed channels accessible via a dropdown menu (`layout.html`) or by using a seearchbar.

TODO:
- [x] Allow users to label their posts
  - [x] Add a label attribute to the post model (`nullable=False, default=None`)
  - [x] add a list of pre-defined labels (`Technology`, `Programming`, `Gaming`, `Food`, `Animals`, `Memes`, etc)
  - [x] Add a label dropdown menu filled by the pre defined labels to the post creation form
  - [ ] #96
- [x] Add a `Tags` Dropdown to `layout.html` all the way on the left in the search bar containing all pre defined tags
- [ ] #95
- [x] Create new pages for all channels showing only posts with a certain topic
